name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Set up Python 3.6 environment
      - name: Set up Python 3.9.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.9.7"
    
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install --dev

      # - restore_cache:
      #     keys:
      #       # when lock file changes, use increasingly general patterns to restore cache
      #       - pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      #       - pip-packages-v1-{{ .Branch }}-
      #       - pip-packages-v1-

      # - save_cache:
      #     paths:
      #       - ~/.local/share/virtualenvs/venv  # this path depends on where pipenv creates a virtualenv
      #     key: pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      #     # Run our unit tests
      - name: Setup virtualenv
        run: |
          pipenv shell

      - name: Run unit tests
        run: |
          python app.py
