name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Set up Python 3.6 environment
      - name: Set up Python 3.9.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.9.7"

      # Install dependencies
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      # - name: Run linter
      #   run: |
      #     pipenv run pylint app.py

      # - restore_cache:
      #     keys:
      #       # when lock file changes, use increasingly general patterns to restore cache
      #       - pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      #       - pip-packages-v1-{{ .Branch }}-
      #       - pip-packages-v1-

      # - save_cache:
      #     paths:
      #       - ~/.local/share/virtualenvs/venv  # this path depends on where pipenv creates a virtualenv
      #     key: pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      #     # Run our unit tests
      - name: Run unit tests
        env:
          CI: true
          MONO_USER: ${{ secrets.MONO_USER }}
          MONGO_PWD: ${{ secrets.MONGO_PWD }}
          ADMIN: ${{ secrets.ADMIN }}
        run: |
          pipenv run python app.py
